// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFrame: typeof import('./../src/components/app-frame.vue')['default']
    AppInner: typeof import('./../src/components/app-inner.vue')['default']
    AppSidebar: typeof import('./../src/components/app-sidebar.vue')['default']
    AppWidget: typeof import('./../src/components/app-widget.vue')['default']
    AppWorkspace: typeof import('./../src/components/app-workspace.vue')['default']
  }
}
